apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: go-api-production
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/YOUR_USER/my-k8s-platform.git
    targetRevision: HEAD
    path: charts/go-api
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: go-api-ns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true