apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-web-app-config
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/YOUR_USER/my-k8s-platform.git
    targetRevision: HEAD
    path: apps/my-web-app  # Points to your deployment/service files
  destination:
    server: https://kubernetes.default.svc
    namespace: my-app-ns   # The namespace where your app will live
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true # Tells Argo to create 'my-app-ns' if it doesn't exist